<a href="https://colab.research.google.com/github/ChristopherIza01/1Matrices/blob/main/1MatricesyDeterminantes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CUADERNO DE ÁLGEBRA LINEAL 
Christopher Joel Iza Amaguaya

MATRICES Y DETERMINANTES


CLASES Y OPERACIONES ENTRE MATRICES

1. Matriz nula: Todos los elementos son cero. Ejemplo: 

   0 0 0
   0 0 0

2. Matriz identidad: Diagonal principal de unos, resto de ceros. Ejemplo: 

   1 0 0
   0 1 0
   0 0 1

3. Matriz simétrica: Matriz igual a su transpuesta. Ejemplo: 

   2 3 4
   3 5 6
   4 6 7

4. Matriz antisimétrica: Matriz transpuesta con elementos cambiados de signo. Ejemplo: 

   0 -2 -5
   2  0 -3
   5  3  0



OPERACIONES ENTRE MATRICES

SUMA DE MATRICES

La suma de matrices consiste en sumar los elementos correspondientes de dos matrices del mismo tamaño. Por ejemplo, si tenemos las matrices:

Matriz A:
1 2
3 4

Matriz B:
5 6
7 8

La suma de estas matrices sería:

Resultado:
6 8
10 12

Cada elemento en el resultado se obtiene sumando los elementos correspondientes de las matrices originales. Es importante destacar que las matrices deben tener la misma dimensión para realizar la suma.

In [ ]:
# Definir las matrices A y B
matriz_A = [[1, 2],
            [3, 4]]

matriz_B = [[5, 6],
            [7, 8]]

# Obtener las dimensiones de las matrices
filas = len(matriz_A)
columnas = len(matriz_A[0])

# Crear una matriz vacía para almacenar el resultado
resultado = [[0 for _ in range(columnas)] for _ in range(filas)]

# Realizar la suma de matrices
for i in range(filas):
    for j in range(columnas):
        resultado[i][j] = matriz_A[i][j] + matriz_B[i][j]

# Imprimir el resultado
print("Resultado:")
for fila in resultado:
    print(fila)


Resultado:
[6, 8]
[10, 12]


PRODUCTO DE UNA MATRIZ POR UN ESCALAR
El producto de una matriz por un escalar consiste en multiplicar cada elemento de la matriz por ese escalar. Esto implica multiplicar cada entrada de la matriz por el número dado, resultando en una matriz donde cada elemento es el resultado de dicha multiplicación.

Ejemplo:
Dada la matriz:
2  4
1  3

Si multiplicamos esta matriz por el escalar 3, obtenemos:
3 * 2   3 * 4
3 * 1   3 * 3

Resultado:
6  12
3  9



In [ ]:
# Definir la matriz
matriz = [[2, 4],
          [1, 3]]

# Definir el escalar
escalar = 3

# Obtener las dimensiones de la matriz
filas = len(matriz)
columnas = len(matriz[0])

# Crear una matriz vacía para almacenar el resultado
resultado = [[0 for _ in range(columnas)] for _ in range(filas)]

# Realizar el producto de la matriz por el escalar
for i in range(filas):
    for j in range(columnas):
        resultado[i][j] = matriz[i][j] * escalar

# Imprimir el resultado
print("Resultado:")
for fila in resultado:
    print(fila)


Resultado:
[6, 12]
[3, 9]


PRODUCTO DE MATRICES
 Consiste en multiplicar cada elemento de una fila de la primera matriz por cada elemento de una columna correspondiente de la segunda matriz, y luego sumar los productos resultantes. 

Ejemplo:
Dadas las matrices:
Matriz A:
1  2
3  4

Matriz B:
5  6
7  8

Para realizar el producto de estas matrices, se multiplica el elemento en la posición (1,1) de la matriz A (que es 1) por el elemento en la posición (1,1) de la matriz B (que es 5), y luego se multiplica el elemento en la posición (1,2) de la matriz A (que es 2) por el elemento en la posición (2,1) de la matriz B (que es 7). Luego, se suman estos productos:

1 * 5 + 2 * 7 = 19

Esto se repite para obtener los demás elementos de la matriz resultante:

1 * 6 + 2 * 8 = 22
3 * 5 + 4 * 7 = 43
3 * 6 + 4 * 8 = 50

Resultado:
19  22
43  50



In [ ]:
# Definir las matrices A y B
matriz_A = [[1, 2],
            [3, 4]]

matriz_B = [[5, 6],
            [7, 8]]

# Obtener las dimensiones de las matrices
filas_A = len(matriz_A)
columnas_A = len(matriz_A[0])
filas_B = len(matriz_B)
columnas_B = len(matriz_B[0])

# Verificar si las matrices pueden multiplicarse
if columnas_A != filas_B:
    print("Error: Las dimensiones de las matrices no permiten la multiplicación.")
else:
    # Crear una matriz vacía para almacenar el resultado
    resultado = [[0 for _ in range(columnas_B)] for _ in range(filas_A)]

    # Realizar el producto de matrices
    for i in range(filas_A):
        for j in range(columnas_B):
            for k in range(columnas_A):
                resultado[i][j] += matriz_A[i][k] * matriz_B[k][j]

    # Imprimir el resultado
    print("Resultado:")
    for fila in resultado:
        print(fila)


Resultado:
[19, 22]
[43, 50]


MATRIZ INVERSA
 La inversa de una matriz se denota como A^(-1).

Ejemplo:
Dada la matriz A:
2  1
1  3

Si encontramos su matriz inversa, A^(-1), y la multiplicamos por la matriz original A, obtendremos la matriz identidad I:

A * A^(-1) = I

Si calculamos la matriz inversa de A, obtenemos:

A^(-1) = (1/5) * [3  -1]
                   [-1  2]

Entonces, si multiplicamos A por su matriz inversa, deberíamos obtener la matriz identidad:

A * A^(-1) = [2  1] * (1/5) * [3  -1] = [1  0]
             [1  3]             [-1  2]     [0  1]

Como resultado, obtenemos la matriz identidad I



In [ ]:
import numpy as np

# Definir la matriz A
matriz_A = np.array([[2, 1],
                     [1, 3]])

# Calcular la matriz inversa
matriz_inversa = np.linalg.inv(matriz_A)

# Imprimir la matriz inversa
print("Matriz inversa:")
print(matriz_inversa)


Matriz inversa:
[[ 0.6 -0.2]
 [-0.2  0.4]]


MATRIZ IDEMPOTENTE
Una matriz idempotente es aquella matriz cuadrada que, cuando se multiplica por sí misma, produce la misma matriz.
Ejemplo:
Matriz A:
1  0
0  1

Si multiplicamos esta matriz por sí misma, obtenemos:
A * A = [[1, 0], [0, 1]] * [[1, 0], [0, 1]] = [[1, 0], [0, 1]]

El resultado es la misma matriz A, lo cual cumple con la propiedad de idempotencia.

MATRIZ ORTOGONAL:
Una matriz ortogonal es aquella matriz cuadrada cuya matriz traspuesta es igual a su matriz inversa. .

Ejemplo:
Matriz B:
0.6  -0.8
0.8   0.6

Si calculamos la matriz traspuesta de B y la multiplicamos por B, deberíamos obtener la matriz identidad:

B^T * B = [[0.6, 0.8], [-0.8, 0.6]] * [[0.6, -0.8], [0.8, 0.6]] = [[1, 0], [0, 1]]

El resultado es la matriz identidad, lo cual cumple con la propiedad de ortogonalidad.

MATRIZ ORTONORMAL:
Una matriz ortonormal es una matriz cuadrada que es tanto ortogonal como compuesta por vectores unitarios. 
Ejemplo:
Matriz C:
1/√2   1/√2
-1/√2  1/√2

Si calculamos la matriz traspuesta de C y la multiplicamos por C, deberíamos obtener la matriz identidad:

C^T * C = [[1/√2, -1/√2], [1/√2, 1/√2]] * [[1/√2, 1/√2], [-1/√2, 1/√2]] = [[1, 0], [0, 1]]

El resultado es la matriz identidad, lo cual cumple con las propiedades de ortogonalidad y ortonormalidad.

SISTEMA DE ECUACIONES

Consideremos el siguiente sistema de ecuaciones de primer grado con dos incógnitas, x e y:

Ecuación 1: 2x + 3y = 8
Ecuación 2: 4x - y = 7

Para resolver este sistema, podemos utilizar diferentes métodos como el método de sustitución, el método de eliminación o la matriz inversa.

Tomemos la primera ecuación y despejemos x en términos de y:

2x = 8 - 3y
x = (8 - 3y) / 2

Sustituyamos este valor de x en la segunda ecuación:

4((8 - 3y) / 2) - y = 7

Simplificando la ecuación, obtenemos:

(16 - 6y) - y = 7
16 - 6y - y = 7
16 - 7y = 7
-7y = 7 - 16
-7y = -9
y = (-9) / (-7)
y = 9/7

Ahora que tenemos el valor de y, sustituyámoslo en la primera ecuación para encontrar el valor de x:

2x + 3(9/7) = 8
2x + 27/7 = 8
2x = 8 - 27/7
2x = (56 - 27) / 7
2x = 29/7
x = (29/7) / 2
x = 29/14

La solución del sistema de ecuaciones es x = 29/14 y y = 9/7.



In [ ]:
import numpy as np

# Definir los coeficientes de las ecuaciones
coeficientes = np.array([[2, 3],
                        [4, -1]])

# Definir los resultados de las ecuaciones
resultados = np.array([8, 7])

# Resolver el sistema de ecuaciones
solucion = np.linalg.solve(coeficientes, resultados)

# Imprimir la solución
print("La solución del sistema de ecuaciones es:")
print("x =", solucion[0])
print("y =", solucion[1])


La solución del sistema de ecuaciones es:
x = 2.0714285714285716
y = 1.2857142857142858


SOLUCIÓN DE SISTEMAS DE ECUACIONES A TRAVÉS DEL MÉTODO DE CRAMER

1. Escribir el sistema de ecuaciones en forma matricial: AX = B, donde A es la matriz de coeficientes, X es el vector de incógnitas y B es el vector de términos independientes.

2. Calcular el determinante de la matriz de coeficientes A. Si el determinante es igual a cero, el sistema no tiene solución única.

3. Para cada incógnita Xi, reemplazar la columna i de A con el vector de términos independientes B y calcular el determinante de la nueva matriz. Esto se llama el determinante de Cramer, denotado como Det(Ai).

4. Calcular el valor de cada incógnita Xi utilizando la fórmula: Xi = Det(Ai) / Det(A), donde Det(A) es el determinante de la matriz de coeficientes original.

Ejemplo:

Consideremos el siguiente sistema de ecuaciones lineales con 2 incógnitas, x e y:

Ecuación 1: 2x + 3y = 8
Ecuación 2: 4x - y = 7

Podemos escribir el sistema en forma matricial: AX = B, donde:

A = [[2, 3],
     [4, -1]]

X = [[x],
     [y]]

B = [[8],
     [7]]

1. Calculamos el determinante de la matriz de coeficientes A:
   Det(A) = (2 * -1) - (3 * 4) = -14

2. Reemplazamos la primera columna de A con el vector de términos independientes B y calculamos el determinante:
   Det(A1) = (8 * -1) - (7 * 4) = -36

   Reemplazamos la segunda columna de A con B y calculamos el determinante:
   Det(A2) = (2 * 7) - (3 * 8) = -10

3. Calculamos el valor de cada incógnita:
   x = Det(A1) / Det(A) = -36 / -14 ≈ 2.57
   y = Det(A2) / Det(A) = -10 / -14 ≈ 0.71

Por lo tanto, la solución del sistema de ecuaciones es x ≈ 2.57 y y ≈ 0.71.



In [ ]:
import numpy as np

def cramer_solver(coefficients, constants):
    n = len(coefficients)
    det_A = np.linalg.det(coefficients)
    solutions = []

    for i in range(n):
        matrix = coefficients.copy()
        matrix[:, i] = constants
        det_Ai = np.linalg.det(matrix)
        solution = det_Ai / det_A
        solutions.append(solution)

    return solutions

# Definir los coeficientes de las ecuaciones
coefficients = np.array([[2, 3],
                         [4, -1]])

# Definir los términos independientes
constants = np.array([8, 7])

# Resolver el sistema de ecuaciones con el método de Cramer
solutions = cramer_solver(coefficients, constants)

# Imprimir las soluciones
print("La solución del sistema de ecuaciones es:")
print("x =", solutions[0])
print("y =", solutions[1])


La solución del sistema de ecuaciones es:
x = 2.0714285714285703
y = 1.2857142857142851


FACTORIZACIÓN POR EL MÉTODO LU

La factorización LU descompone una matriz cuadrada en el producto de una matriz triangular inferior (L) y una matriz triangular superior (U). Es útil para resolver sistemas de ecuaciones y calcular determinantes e inversas de matrices.

Ejemplo:
Consideremos la siguiente matriz A:

A = [[2, 1, -1],
     [-4, -2, 5],
     [-2, 1, 3]]

Aplicando la factorización LU, obtenemos:

L = [[1, 0, 0],
     [-2, 1, 0],
     [-1, -3, 1]]

U = [[2, 1, -1],
     [0, -4, 3],
     [0, 0, 1]]

La matriz A se descompone en el producto LU, es decir, A = LU.

Ahora, supongamos que tenemos el siguiente sistema de ecuaciones: 

2x + y - z = 8
-4x - 2y + 5z = -3
-2x + y + 3z = 5

Podemos resolver este sistema utilizando la factorización LU:

1. Resolver Ly = b, donde L es la matriz triangular inferior y b es el vector de términos independientes:

1y = 8
-2y + 1z = -3
-1y - 3z = 5

La solución es y = 8, z = 1 y = -3.

2. Resolver Ux = y, donde U es la matriz triangular superior y y es el vector de soluciones obtenido en el paso anterior:

2x + 1y - 1z = 8
0x - 4y + 3z = -3
0x + 0y + 1z = 1

La solución es x = 2, y = -1 y z = 1.

Por lo tanto, la solución del sistema de ecuaciones es x = 2, y = -1 y z = 1 utilizando la factorización LU.



In [ ]:
import numpy as np
import sympy as sym
import math
#Ejercicio 1
A = sym.Matrix ([[1,2,-3],[0,1,2],[-1,2,0]])
B = sym.Matrix ([[-1,2,0],[0,1,2],[1,2,-3]])
C = sym.Matrix ([[0,4,-3],[0,1,2],[-1,2,0]])
#Literal a Hallar un E1 tal que, E1*A=b
E1 = sym.Matrix ([[0,0,1],[0,1,0],[1,0,0]])
r = np.dot(E1,A)
print(r)
#Literal b. Hallar un E2 tal que, E2*C=A
E2 = sym.Matrix ([[1,0,-1],[0,1,0],[0,0,1]])
q = np.dot(E2,C)
print(q)
#Literal c. Hallar un E3 tal que, E3*B=A
E3= sym.Matrix ([[0,0,1],[0,1,0],[1,0,0]])
t = np.dot(E3,B)
print(t)

[[-1 2 0]
 [0 1 2]
 [1 2 -3]]
[[1 2 -3]
 [0 1 2]
 [-1 2 0]]
[[1 2 -3]
 [0 1 2]
 [-1 2 0]]


In [ ]:
#Ejercicio 2 Reemplazamos los valores de nos diron como resultado para comprobar cuando:
#a. EL sistema no posee solucion
raiz = math.sqrt(3)
D = sym.Matrix ([[raiz,raiz-3,4,0],[-1,raiz-1,raiz+1,0],[-2,-2,1,0]])
D.rref(pivots=False)

Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0]])

In [ ]:
#b. El sistema posee infinitas soluciones
raiz2 = math.sqrt(46)
print(raiz2)
E = sym.Matrix ([[-7-raiz2 ,-10-raiz2,4,0],[-1,-8-raiz2,-raiz2-6,0],[-2,-2,1,0]])
E.rref(pivots=False)

6.782329983125268


Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0]])

In [ ]:
#c. Existe una unica solucion
F = sym.Matrix ([[1,-2,4,0],[-1,0,2,0],[-2,-2,1,0]])
F.rref(pivots=False)

Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0]])

In [ ]:
#Ejercicio 3 Factorizacion LU
#a.
A1= sym.Matrix ([[1,0],[-2,1]])
print(A1)
L1 = sym.Matrix ([[1, 0],[-2, 1]])
U1 = sym.Matrix ([[1, 0],[0, 1]])
a = np.dot(L1,U1)
print(a)

Matrix([[1, 0], [-2, 1]])
[[1 0]
 [-2 1]]


In [ ]:
#b.
B2 = sym.Matrix ([[2,0,0],[0,-3,1],[10,12,3]])
print(B2)
L2 = sym.Matrix ([[1,0,0],[0,1,0],[5,-4,1]])
U2 = sym.Matrix ([[2,0,0],[0,-3,1],[0,0,7]])
m = np.dot(L2,U2)
print(m)

Matrix([[2, 0, 0], [0, -3, 1], [10, 12, 3]])
[[2 0 0]
 [0 -3 1]
 [10 12 3]]


In [ ]:
#c.
C2 = sym.Matrix ([[3,0,1],[6,1,1],[-3,1,0]])
print(C2)
L3 = sym.Matrix ([[1,0,0],[2,1,0],[-1,1,1]])
U3 = sym.Matrix ([[3,0,1],[0,1,-1],[0,0,2]])
e = np.dot(L3,U3)
print(e)

Matrix([[3, 0, 1], [6, 1, 1], [-3, 1, 0]])
[[3 0 1]
 [6 1 1]
 [-3 1 0]]


In [ ]:
# 4 Resolver el sistema usando LU
#a. EL sistema
A3 = sym.Matrix ([[2,1,0],[0,1,-1],[-2,1,1]])
print(A3)
L4 = sym.Matrix ([[1,0,0],[0,1,0],[-1,2,1]])
U4 = sym.Matrix ([[2,1,0],[0,1,-1],[0,0,3]])
l = np.dot(L3,U3)
print(l)
#Creamos la segunda matriz para solucionar
S1 = sym.Matrix ([[1,1,0,1],[0,1,0,2],[-1,2,1,-2]])
print(S1)
#Resolvemos el sistema
# a=1, b=2, c=-5
#Con estas nuevas reoslucion ampliamos con la matriz U4, para hallar la solucion al problema
U4R = sym.Matrix ([[2,1,0,1],[0,1,-1,2],[0,0,3,-5]])
#Al despejar las respuestas son
z = -5/3
y = 2-(5/3)
x = (1-(1/3))/2
print("La solución del sistema es:")
print(x)
print(y)
print(z)

Matrix([[2, 1, 0], [0, 1, -1], [-2, 1, 1]])
[[3 0 1]
 [6 1 1]
 [-3 1 0]]
Matrix([[1, 1, 0, 1], [0, 1, 0, 2], [-1, 2, 1, -2]])
La solución del sistema es:
0.33333333333333337
0.33333333333333326
-1.6666666666666667


In [ ]:
# 4 Resolver el sistema usando LU
#b. EL sistema
B3 = sym.Matrix ([[2,0,2],[-2,1,-1],[6,2,1]])
print(B3)
L5 = sym.Matrix ([[1,0,0],[-1,1,0],[3,2,1]])
U5 = sym.Matrix ([[2,0,2],[0,1,1],[0,0,7]])
ia = np.dot(L5,U5)
print(ia)
#Creamos la segunda matriz para solucionar
S2 = sym.Matrix ([[1,0,0,4],[-1,1,0,-4],[3,2,1,20]])
print(S2)
#Resolvemos el sistema
# a=4, b=0, c=8
#Con estas nuevas reoslucion ampliamos con la matriz U4, para hallar la solucion al problema
U5R = sym.Matrix ([[2,0,2,4],[0,1,1,0],[0,0,-7,8]])
#Al despejar las respuestas son
z2 = -(8/7)
y2 = -z2
x2 = ((16/7)+4) * (1/2)
print("La solución del sistema es:")
print(x2)
print(y2)
print(z2)

Matrix([[2, 0, 2], [-2, 1, -1], [6, 2, 1]])
[[2 0 2]
 [-2 1 -1]
 [6 2 15]]
Matrix([[1, 0, 0, 4], [-1, 1, 0, -4], [3, 2, 1, 20]])
La solución del sistema es:
3.142857142857143
1.1428571428571428
-1.1428571428571428


MATRIZ ELEMENTAL

es una matriz cuadrada que se obtiene al realizar una única operación elemental de fila en una matriz de identidad.

Ejemplo:
Consideremos la siguiente matriz de identidad 3x3:

I = [[1, 0, 0],
     [0, 1, 0],
     [0, 0, 1]]

Aplicaremos una operación elemental de fila para intercambiar la primera y la segunda fila. La matriz elemental correspondiente a esta operación es:

E = [[0, 1, 0],
     [1, 0, 0],
     [0, 0, 1]]

Al multiplicar la matriz E con la matriz I, obtenemos la matriz transformada:

E * I = [[0, 1, 0],
         [1, 0, 0],
         [0, 0, 1]]

La matriz transformada intercambia la primera y la segunda fila de la matriz original de identidad.


In [ ]:
import numpy as np

def apply_elementary_matrix(matrix, elementary_matrix):
    transformed_matrix = elementary_matrix.dot(matrix)
    return transformed_matrix

# Matriz original
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Matriz elemental (intercambio de filas 1 y 2)
elementary_matrix = np.array([[0, 1, 0],
                              [1, 0, 0],
                              [0, 0, 1]])

# Aplicar la matriz elemental a la matriz original
transformed_matrix = apply_elementary_matrix(matrix, elementary_matrix)

# Imprimir la matriz transformada
print("Matriz original:\n", matrix)
print("\nMatriz transformada:\n", transformed_matrix)


Matriz original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriz transformada:
 [[4 5 6]
 [1 2 3]
 [7 8 9]]
