<a href="https://colab.research.google.com/github/ChristopherIza01/1Matrices/blob/main/2EspaciosVectoriales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SUBESPACIOS VECTORIALES

2. Subespacios vectoriales
Dado un espacio vectorial V , decimos que un subconjunto no vacIo U ⊆ V , es un subespacio vectorial de V cuando al restringir las operaciones de suma y multiplicacion por
escalares para V a U, este es un espacio vectorial. Formalmente, lo que estamos diciendo
es que:
1. Para cualesquiera u, v ∈ U, se verifica que u + v ∈ U
2. Para cualesquiera λ ∈ K, u ∈ U se verifica que λ · u ∈ U
Observar que la segunda condicion anterior implica que el vector cero de V esta tambiEn
en U, ya que si u ∈ U, entonces 0 · u =
−→0 ∈ U.
Propiedad 5. U es un subespacio vectorial de V si y solo si ∀u, v ∈ U y ∀λ, µ ∈ K se
verifica que λu + µv ∈ U.
3
Todo espacio vectorial V tiene siempre los subespacios vectoriales V y {
−→0 }, los cuales
se denominan los subespacios vectoriales triviales de V . Un subespacio de V se dice
propio si no es ninguno de los subespacios triviales.
Ejemplo 6. Comprobamos que el subconjunto U = {(x, y, z) ∈ R
3
| 2x − y + 5z = 0} es
un subespacio vectorial de R
3
.
En primer lugar observamos que U es no vacIo ya que (0, 0, 0) ∈ U. Si u = (x1, y1, z1), v =
(x2, y2, z2) ∈ U, y λ, µ ∈ R, entonces λu + µv = (λx1 + µx2, λy1 + µy2, λz1 + µz2), el cual
pertenece de nuevo a U, ya que
2(λx1 +µx2)−(λy1 +µy2)+5(λz1 +µz2) = λ(2x1−y1 +5z1)+µ(2x2−y2 +5z2) = 0+0 = 0
Mas generalmente, se puede comprobar que todo sistema homogeneo de ecuaciones lineales en n incognitas y con coeficientes en K, determina un subespacio vectorial de Kn
.


In [ ]:
import numpy as np

def is_subspace(vectors):
    # Convertir la lista de vectores en una matriz
    matrix = np.array(vectors)

    # Verificar la cerradura bajo la suma
    if np.all(np.sum(matrix, axis=0) == 0):
        # Verificar la cerradura bajo la multiplicación por un escalar
        if np.all(np.multiply(matrix, 2) == -matrix):
            return True

    return False

# Ejemplo 1: Conjunto de vectores que forman un subespacio vectorial
vectors1 = [[1, 2, -1], [-3, 0, 2], [2, -2, 1]]
print("¿El conjunto 1 forma un subespacio vectorial?", is_subspace(vectors1))

# Ejemplo 2: Conjunto de vectores que no forman un subespacio vectorial
vectors2 = [[1, 2, -1], [-3, 0, 2], [2, -2, 0]]
print("¿El conjunto 2 forma un subespacio vectorial?", is_subspace(vectors2))


¿El conjunto 1 forma un subespacio vectorial? False
¿El conjunto 2 forma un subespacio vectorial? False


In [ ]:
import numpy as np

def is_subspace(vectors):
    # Convertir la lista de vectores en una matriz
    matrix = np.array(vectors)

    # Verificar la cerradura bajo la suma
    sum_vector = np.sum(matrix, axis=0)
    if np.all(sum_vector == np.zeros_like(sum_vector)):
        # Verificar la cerradura bajo la multiplicación por un escalar
        scalar = 2
        scalar_multiplication = scalar * matrix
        if np.all(scalar_multiplication == np.zeros_like(scalar_multiplication)):
            return True

    return False

# Ejemplo: Conjunto de vectores que forman un subespacio vectorial
vectors = [[1, 2, -1], [-3, 0, 2], [2, -4, 2]]
print("¿El conjunto forma un subespacio vectorial?", is_subspace(vectors))


¿El conjunto forma un subespacio vectorial? False


CONJUNTOS LINEALMENTE DEPENDIENTES E INDEPENDIENTES


Ejemplo:

Consideremos el conjunto de vectores V = {[1, 2], [3, 4], [5, 6]} en R².

1. Linealmente Dependiente:
Si expresamos el primer vector [1, 2] como combinación lineal de los otros dos vectores, podemos obtener:

[1, 2] = 2 * [3, 4] - [5, 6]

Esto muestra que el vector [1, 2] puede ser expresado como combinación lineal de los vectores [3, 4] y [5, 6]. Por lo tanto, el conjunto V es linealmente dependiente.

2. Linealmente Independiente:
Si intentamos expresar cualquier vector del conjunto [3, 4] o [5, 6] como combinación lineal de los otros dos, no es posible encontrar una combinación de escalares que cumpla esa igualdad. Por lo tanto, los vectores [3, 4] y [5, 6] no pueden ser expresados como combinación lineal de los otros vectores. Esto indica que el conjunto V es linealmente independiente.



In [ ]:
import numpy as np

def is_linearly_dependent(vectors):
    # Convertir los vectores en una matriz
    matrix = np.array(vectors)

    # Verificar si la matriz tiene rango completo
    rank = np.linalg.matrix_rank(matrix)
    if rank < len(vectors):
        return True

    return False

# Ejemplo de conjunto linealmente dependiente
vectors_dependent = [[1, 2, 3], [2, 4, 6], [3, 6, 9]]
print("¿El conjunto es linealmente dependiente?", is_linearly_dependent(vectors_dependent))

# Ejemplo de conjunto linealmente independiente
vectors_independent = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
print("¿El conjunto es linealmente independiente?", is_linearly_dependent(vectors_independent))


¿El conjunto es linealmente dependiente? True
¿El conjunto es linealmente independiente? False


BASE Y DIMENSIÓN 

Ejercicio:
Consideremos el siguiente sistema de ecuaciones lineales:


2x + y - z = 0
x - y + 3z = 0
3x + 2y + 5z = 0
Para determinar la dimensión y una base del espacio generado por este sistema de ecuaciones, podemos encontrar las soluciones del sistema y observar el número de variables libres.

Solución:
Primero, escribimos el sistema de ecuaciones en forma matricial: AX = 0, donde A es la matriz de coeficientes y X es el vector de incógnitas.

A = [[2, 1, -1],
     [1, -1, 3],
     [3, 2, 5]]

X = [[x],
     [y],
     [z]]

0 = [[0],
     [0],
     [0]]
Usando eliminación gaussiana o métodos similares, reducimos la matriz aumentada [A | 0] a su forma escalonada reducida. Al hacerlo, encontramos que la última columna es una columna pivote, lo que indica que hay una variable libre.


R = [[1, 0, 1],
     [0, 1, -1],
     [0, 0, 0]]
La tercera columna corresponde a la variable z, que es una variable libre. Por lo tanto, la dimensión del espacio generado por este sistema de ecuaciones es 2 (el número de variables que no son libres).

Para encontrar una base del espacio generado, asignamos una variable libre a 1 y las variables no libres a 0. Esto nos dará los vectores que formarán la base.

Tomando z = 1, obtenemos:


x = -1
y = 1
El vector correspondiente es [-1, 1, 1].

Tomando z = 0, obtenemos:

x = 1
y = -1
El vector correspondiente es [1, -1, 0].

Por lo tanto, una base del espacio generado por el sistema de ecuaciones es {[1, -1, 0], [-1, 1, 1]}.

En resumen, la dimensión del espacio generado por el sistema de ecuaciones es 2, y una base correspondiente es {[1, -1, 0], [-1, 1, 1]}.

In [ ]:
import numpy as np

def find_dimension_and_base(coefficients):
    A = np.array(coefficients)
    _, _, V = np.linalg.svd(A)
    null_space = V[-1, :]
    dimension = len(null_space) - np.count_nonzero(null_space)
    base = []
    for i in range(dimension):
        vector = np.random.randint(-10, 10, size=len(null_space))
        while np.dot(vector, null_space) != 0:
            vector = np.random.randint(-10, 10, size=len(null_space))
        base.append(vector.tolist())
    
    return dimension, base

# Ejercicio de dimensión y base
coefficients = [[2, 1, -1], [1, -1, 3], [3, 2, 5]]
dimension, base = find_dimension_and_base(coefficients)

print("Dimensión del espacio generado:", dimension)
print("Base del espacio generado:", base)


Dimensión del espacio generado: 0
Base del espacio generado: []


VECTORES ORTOGONALES

- Dos vectores son ortogonales si su producto escalar es cero.
- En un espacio vectorial, un conjunto de vectores es ortogonal si todos los pares de vectores en el conjunto son ortogonales entre sí.
- Un conjunto de vectores ortogonales es linealmente independiente.

Ejercicio:
Consideremos los siguientes vectores en R³:

v₁ = [1, 0, -1]
v₂ = [2, -3, 4]
v₃ = [0, 1, 1]

Para determinar si estos vectores son ortogonales, podemos calcular su producto escalar.

El producto escalar entre dos vectores u y v se calcula sumando el producto de sus componentes correspondientes:

u · v = u₁ * v₁ + u₂ * v₂ + u₃ * v₃

Calculamos el producto escalar entre todos los pares de vectores:

v₁ · v₂ = 1 * 2 + 0 * (-3) + (-1) * 4 = 2 + 0 - 4 = -2
v₁ · v₃ = 1 * 0 + 0 * 1 + (-1) * 1 = 0 + 0 - 1 = -1
v₂ · v₃ = 2 * 0 + (-3) * 1 + 4 * 1 = 0 - 3 + 4 = 1

Los resultados muestran que el producto escalar entre los vectores v₁ y v₂ es -2, entre v₁ y v₃ es -1, y entre v₂ y v₃ es 1. Ninguno de los productos escalares es igual a cero. Por lo tanto, concluimos que los vectores v₁, v₂ y v₃ no son ortogonales entre sí.

In [ ]:
import numpy as np

def check_orthogonal(vectors):
    n = len(vectors)
    for i in range(n):
        for j in range(i+1, n):
            if np.dot(vectors[i], vectors[j]) != 0:
                return False
    return True

# Ejercicio de vectores ortogonales
vectors = np.array([[1, 0, -1], [2, -3, 4], [0, 1, 1]])

if check_orthogonal(vectors):
    print("Los vectores son ortogonales entre sí.")
else:
    print("Los vectores no son ortogonales entre sí.")


Los vectores no son ortogonales entre sí.


In [ ]:
import numpy as np

def check_orthogonal(vectors):
    n = len(vectors)
    for i in range(n):
        for j in range(i+1, n):
            if np.dot(vectors[i], vectors[j]) != 0:
                return False
    return True

# Ejemplo de vectores ortogonales
vectors = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

if check_orthogonal(vectors):
    print("Los vectores son ortogonales entre sí.")
else:
    print("Los vectores no son ortogonales entre sí.")


Los vectores son ortogonales entre sí.


VECTORES ORTONORMALES

Ejercicio:

Encuentra un conjunto de tres vectores ortonormales en R³.

Solución:

Para construir un conjunto de vectores ortonormales, podemos tomar tres vectores linealmente independientes y normalizarlos dividiéndolos por su longitud.

Tomemos los siguientes vectores:

v₁ = [1, 1, 0]
v₂ = [-1, 1, 0]
v₃ = [0, 0, 1]

Primero, verifiquemos si los vectores son linealmente independientes. Podemos hacerlo calculando su determinante:

| 1  1  0 |
|-1  1  0 | = 2 ≠ 0
| 0  0  1 |

El determinante es distinto de cero, lo que indica que los vectores son linealmente independientes.

A continuación, normalizaremos los vectores dividiéndolos por su longitud:

v₁' = v₁ / ||v₁|| = [1/√2, 1/√2, 0]
v₂' = v₂ / ||v₂|| = [-1/√2, 1/√2, 0]
v₃' = v₃ / ||v₃|| = [0, 0, 1]

Finalmente, comprobemos que los vectores resultantes son ortogonales entre sí:

v₁' · v₂' = (1/√2)(-1/√2) + (1/√2)(1/√2) + 0 = 0
v₁' · v₃' = (1/√2)(0) + (1/√2)(0) + 0 = 0
v₂' · v₃' = (-1/√2)(0) + (1/√2)(0) + 0 = 0

Todos los productos escalares son cero, lo que indica que los vectores son ortogonales entre sí.

Por lo tanto, el conjunto de vectores ortonormales en R³ es:

v₁' = [1/√2, 1/√2, 0]
v₂' = [-1/√2, 1/√2, 0]
v₃' = [0, 0, 1]

Estos vectores forman una base ortonormal en R³.

In [ ]:
import numpy as np

# Ejercicio de resolución de vectores orthonormales
v1 = np.array([1, 0, -1])
v2 = np.array([0, 1, 1])
v3 = np.array([-1, 2, -1])

# Paso 1: Ortogonalización
u1 = v1
u2 = v2 - (np.dot(v2, u1) / np.dot(u1, u1)) * u1
u3 = v3 - (np.dot(v3, u1) / np.dot(u1, u1)) * u1 - (np.dot(v3, u2) / np.dot(u2, u2)) * u2

# Paso 2: Normalización
v1_ortho = u1 / np.linalg.norm(u1)
v2_ortho = u2 / np.linalg.norm(u2)
v3_ortho = u3 / np.linalg.norm(u3)

print("Vectores Ortonormales:")
print(v1_ortho)
print(v2_ortho)
print(v3_ortho)



Vectores Ortonormales:
[ 0.70710678  0.         -0.70710678]
[0.40824829 0.81649658 0.40824829]
[-0.57735027  0.57735027 -0.57735027]


In [ ]:
import numpy as np

# Ejercicio de resolución de vectores orthonormales
v1 = np.array([1, -1])
v2 = np.array([3, 2])

# Paso 1: Ortogonalización
u1 = v1
u2 = v2 - (np.dot(v2, u1) / np.dot(u1, u1)) * u1

# Paso 2: Normalización
v1_ortho = u1 / np.linalg.norm(u1)
v2_ortho = u2 / np.linalg.norm(u2)

print("Vectores Ortonormales:")
print(v1_ortho)
print(v2_ortho)


Vectores Ortonormales:
[ 0.70710678 -0.70710678]
[0.70710678 0.70710678]


PROCESO DE ORTOGONALIZACIÓN POR EL MÉTODO GRAM-SCHMIDT

Supongamos que tenemos los siguientes vectores en ℝ³:

v₁ = (1, 1, 0)
v₂ = (1, 0, 1)
v₃ = (0, 1, 1)


Paso 1: Normalización del primer vector
El primer vector v₁ ya está normalizado, por lo que no es necesario realizar ningún cálculo adicional.

Paso 2: Proyección y ortogonalización del segundo vector
Calculamos la proyección de v₂ sobre v₁ utilizando la siguiente fórmula:
projₓᵥᵢ = (⟨vᵢ, x⟩ / ⟨x, x⟩) * x

Para encontrar el vector ortogonalizado u₂, restamos la proyección al vector original:
u₂ = v₂ - projₓᵥ₂

Calculamos los productos internos necesarios:
⟨v₁, v₂⟩ = (1 * 1) + (1 * 0) + (0 * 1) = 1
⟨v₁, v₁⟩ = (1 * 1) + (1 * 1) + (0 * 0) = 2

Calculamos la proyección:
projᵥ₁ᵥ₂ = (⟨v₁, v₂⟩ / ⟨v₁, v₁⟩) * v₁ = (1 / 2) * (1, 1, 0) = (0.5, 0.5, 0)

Calculamos el vector ortogonalizado:
u₂ = v₂ - projᵥ₁ᵥ₂ = (1, 0, 1) - (0.5, 0.5, 0) = (0.5, -0.5, 1)

Paso 3: Proyección y ortogonalización del tercer vector
Calculamos las proyecciones de v₃ sobre v₁ y v₂:
projᵥ₁ᵥ₃ = (⟨v₁, v₃⟩ / ⟨v₁, v₁⟩) * v₁ = (1 / 2) * (1, 1, 0) = (0.5, 0.5, 0)
projᵥ₂ᵥ₃ = (⟨v₂, v₃⟩ / ⟨v₂, v₂⟩) * v₂ = (1 / 2) * (0.5, -0.5, 1) = (0.25, -0.25, 0.5)

Calculamos el vector ortogonalizado:
u₃ = v₃ - projᵥ₁ᵥ₃ - projᵥ₂ᵥ₃ = (0, 1, 1) - (0.5, 0.5, 0) - (0.25, -0.25, 0.5) = (-0.75, 0.75, 0.5)

Ahora tenemos los vectores ortogonalizados:
u₁ = (1, 1, 0)
u₂ = (0.)